backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Read Time", name: "readtime", widget: "string", default: "5 min read"}
      - {label: "Body", name: "body", widget: "markdown"}
